project:
  type: website
  output-dir: docs

website:
  title: GVPT729
  navbar:
    background: maroon
    foreground: white
    left:
      - text: "Home"
        href: https://johannabirnir.com/
      - text: "Teaching"
        href: https://johannabirnir.com/teaching.html
      - text: "GVPT729"
        href: index.qmd #href	Link to file contained with the project or external URL.


format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

